print("Expression Tester")
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("\nArithmetic results:")
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a % b =", a % b)

print("\nComparison results:")
print("a == b →", a == b)
print("a != b →", a != b)
print("a > b  →", a > b)
print("a < b  →", a < b)

print("\nLogical results:")
print("(a > 0) and (b > 0) →", (a > 0) and (b > 0))
print("(a < 0) or (b < 0)  →", (a < 0) or (b < 0))
print("not (a == b)        →", not (a == b))
